version: "3.7"

volumes:
  pgdata:
    driver: local

services:
  database:
    container_name: postgres-realityquest-db
    image: postgres:${POSTGRES_VERSION}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data




