version: "3.7"

volumes:
  pgdata:
    driver: local


services:
  database:
    container_name: postgres-realityquest-db
    image: postgres:${POSTGRES_VERSION}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: reality-quest
    container_name: app
    depends_on: [database, keycloak]
    ports:
      - "8081:8081"

  keycloak:
    image: jboss/keycloak
    container_name: local-keycloak
    ports:
      - "8024:8080"
    volumes:
      - ./imports:/tmp/import
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    command:
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/tmp/import"




